name: Shankar
favicon: null
layout_spectrum: 0.37608343781903386
typography_spectrum: 0.91621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#514a50'
    - '#cccccc'
    - '#1e1d22'
    - '#7c7778'
  brandStrength: 0.6875
  lightness: 0.5800708171445876
  saturation: 0.6755513814277947
  rhythmicContrast: 0.251337111229077
purpose: []
